[package]
name = "lb_pair"
version = "0.1.0"
edition = "2021"
exclude = [
  # Those files are contract-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
libraries= { path = "../../libraries" }
interfaces = { path = "../../interfaces" }
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret", features = ["stargate"] }
cosmwasm-storage = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret" }
cosmwasm-schema = { version = "1.2" }
# schemars = { version = "0.8" }
serde = { version = "1" }
serde-json-wasm = { version = "0.5"}
thiserror = { version = "1" }
secret-toolkit = { git = "https://github.com/scrtlabs/secret-toolkit", tag = "v0.8.1", default-features = false, features = ["storage"] }
# cw-storage-plus = { version = "1", default-features = false, features = ["macro"] }
ethnum = { version = "1" }

[dev-dependencies]
anyhow = "1"
# cw-multi-test = { version = "0.16.0", default-features = false }

[[bin]]
name = "schema"
