[workspace]
members = [
  "packages/lb_interfaces",
  "packages/lb_libraries",
  "contracts/lb_factory",
  "contracts/lb_pair",
  "contracts/lb_quoter",
  "contracts/lb_token",
  "contracts/lb_router",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
lb-interfaces = { path = "packages/lb_interfaces" }
lb-libraries = { path = "packages/lb_libraries" }
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.10" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "1.1.10" }
cosmwasm-schema = { version = "1.4" }
schemars = { version = "0.8.13" }
serde = { version = "1.0" }
serde-json-wasm = { version = "1.0" }
secret-toolkit = { version = "0.9", features = ["storage"] }
# cw-storage-plus = { version = "1", default-features = false, features = ["macro"] }
ethnum = { version = "1.4" }
thiserror = { version = "1.0" }
anyhow = "1.0"
primitive-types = { version = "0.12.2", default-features = false }
