[workspace]
members = [
  "packages/interfaces",
  "packages/libraries",
  "contracts/lb-factory",
  "contracts/lb-pair",
  "contracts/lb-quoter",
  "contracts/lb-token",
  "contracts/lb-router",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[patch.crates-io]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret" }
