[workspace]
members = [
  "packages/lb_interfaces",
  "packages/lb_libraries",
  "contracts/lb_factory",
  "contracts/lb_pair",
  "contracts/lb_quoter",
  "contracts/lb_token",
  "contracts/lb_router",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[patch.crates-io]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret" }


