[package]
name = "lb-libraries"
version = "0.14.0"
authors = ["Kent, Haseeb"]
edition = "2021"
description = "Helper libraries for liquidity book contracts"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret", features = [
  "stargate",
] }
cosmwasm-schema = { version = "1.2" }
serde = { version = "1" }
thiserror = { version = "1" }
ethnum = { version = "1" }
