[alias]
deploy = "run -p lb-deployer"
schema = "run -p lb-schema"
secretcli = "run -p lb-secretcli"

[build]
# target = "wasm32-unknown-unknown"
# rustflags = "-C link-arg=-s"

[check]
# target = "x86_64-unknown-linux-gnu"
