[package]
name = "lb-libraries"
version = "0.1.0"
authors = ["Kent", "Haseeb Saeed <itsHaseebSaeed@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
secret-toolkit = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ethnum = { workspace = true }
primitive-types = { workspace = true }

secret-storage-plus = { git = "https://github.com/securesecrets/secret-plus-utils" }

[dev-dependencies]
lb-interfaces = { workspace = true }
