[book]
authors = ["kent-3"]
language = "en"
multilingual = false
src = "src"
title = "Liquidity Book"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/kent-3/liquidity-book"
edit-url-template = "https://github.com/kent-3/liquidity-book/edit/main/docs/{path}"
