[book]
authors = ["kent-3"]
language = "en"
multilingual = false
src = "src"
title = "Liquidity Book"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/kent-3/liquidity-book"
edit-url-template = "https://github.com/kent-3/liquidity-book/edit/main/docs/{path}"
no-section-label = true

[output.html.fold]
enable = true # whether or not to enable section folding
level = 1     # the depth to start folding
