name: Deploy mdBook Docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"
permissions:
  contents: write # To push a branch
  pull-requests: write # To create a PR from that branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
      - run: (test -x $HOME/.cargo/bin/mdbook-tabs || cargo install --vers "^0.2" mdbook-tabs)
      - run: mdbook build docs && mdbook test docs
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/book # The folder the action should deploy.
          target-folder: docs/
